### ISSUE TITLE
Latest version on readme example

### ISSUE THREAD

**Issue by hongkongkiwi** [sirosen/texthooks#11]
I recommend to update your README with the latest version e.g.

```
- repo: https://github.com/sirosen/texthooks
  rev: 0.3.1
  hooks:
    - id: fix-smartquotes
    - id: fix-ligatures
```
